### ISSUE TITLE
Comment for the port number disagrees with the actual port

### ISSUE THREAD

**Issue by dvberkel** [noha/prolog-todo-web-app#1]
Hi @noha,
Love your work. While inspecting it I noticed that the comment telling on which port the server will be hosted disagrees with the argument. Nothing big, but it could have some people scratching their heads

**Comment by noha** [comment]
Haha, you should love the code because I stole the session stuff from you ;) 
Haha, yes, I just changed the port because the server was working regardless what I was doing and then I tried to change the port to see if it changes something and forgot to switch back :)
Thanks for noting!

**Comment by dvberkel** [comment]
That is not stealing, that is sharing :+1: 

How else do we learn?
